import { Movement, MovementDifficulty, MovementId, MovementType, MuscleGroup } from './types';

export const movements: Movement[] = [
  {
    id: 'pu',
    name: 'Pull-up',
    shortName: 'PU',
    difficulty: MovementDifficulty.MEDIUM,
    equipment: 'Pull-up Bar',
    primaryMuscleGroup: MuscleGroup.LAT,
    secondaryMuscleGroup: MuscleGroup.BICEPS,
    type: MovementType.GYMNASTICS,
    referenceReps: '10',
  },
  {
    id: 'c2b',
    name: 'Chest-to-Bar Pull-up',
    shortName: 'C2B',
    difficulty: MovementDifficulty.HARD,
    equipment: 'Pull-up Bar',
    primaryMuscleGroup: MuscleGroup.LAT,
    secondaryMuscleGroup: MuscleGroup.BICEPS,
    type: MovementType.GYMNASTICS,
    referenceReps: '10',
  },
  {
    id: 'mu',
    name: 'Muscle-up',
    shortName: 'MU',
    difficulty: MovementDifficulty.HARD,
    equipment: 'Rings or Bar',
    primaryMuscleGroup: MuscleGroup.LAT,
    secondaryMuscleGroup: MuscleGroup.TRICEPS,
    type: MovementType.GYMNASTICS,
    referenceReps: '10',
  },
  {
    id: 'hspu',
    name: 'Handstand Push-up',
    shortName: 'HSPU',
    difficulty: MovementDifficulty.HARD,
    equipment: 'None',
    primaryMuscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscleGroup: MuscleGroup.TRICEPS,
    type: MovementType.GYMNASTICS,
    referenceReps: '10',
  },
  {
    id: 'kbs',
    name: 'Kettlebell Swing',
    shortName: 'KBS',
    difficulty: MovementDifficulty.MEDIUM,
    equipment: 'Kettlebell',
    primaryMuscleGroup: MuscleGroup.GLUTES,
    secondaryMuscleGroup: MuscleGroup.SHOULDERS,
    type: MovementType.WEIGHTLIFTING,
    referenceWeight: '24/16 kg',
    referenceReps: '20',
  },
  {
    id: 'sn',
    name: 'Snatch',
    shortName: 'SN',
    difficulty: MovementDifficulty.ELITE,
    equipment: 'Barbell',
    primaryMuscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscleGroup: MuscleGroup.GLUTES,
    type: MovementType.WEIGHTLIFTING,
    referenceWeight: '50/35 kg',
    referenceReps: '10',
  },
  {
    id: 'C&j',
    name: 'Clean and Jerk',
    shortName: 'C&J',
    difficulty: MovementDifficulty.ELITE,
    equipment: 'Barbell',
    primaryMuscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscleGroup: MuscleGroup.QUADRICEPS,
    type: MovementType.WEIGHTLIFTING,
    referenceWeight: '60/40 kg',
    referenceReps: '10',
  },
  {
    id: 'dl',
    name: 'Deadlift',
    shortName: 'DL',
    difficulty: MovementDifficulty.MEDIUM,
    equipment: 'Barbell',
    primaryMuscleGroup: MuscleGroup.LOWER_BACK,
    secondaryMuscleGroup: MuscleGroup.HAMSTRINGS,
    type: MovementType.POWERLIFTING,
    referenceWeight: '100/70 kg',
    referenceReps: '10',
  },
  {
    id: 'bj',
    name: 'Box Jump',
    shortName: 'BJ',
    difficulty: MovementDifficulty.MEDIUM,
    equipment: 'Box',
    primaryMuscleGroup: MuscleGroup.QUADRICEPS,
    secondaryMuscleGroup: MuscleGroup.CALVES,
    type: MovementType.GYMNASTICS,
    referenceReps: '20',
  },
  {
    id: 'bur',
    name: 'Burpee',
    shortName: 'BUR',
    difficulty: MovementDifficulty.MEDIUM,
    equipment: 'None',
    primaryMuscleGroup: MuscleGroup.CHEST,
    secondaryMuscleGroup: MuscleGroup.QUADRICEPS,
    type: MovementType.GYMNASTICS,
    referenceReps: '20',
  },
  {
    id: 'row',
    name: 'Rowing',
    shortName: 'ROW',
    difficulty: MovementDifficulty.EASY,
    equipment: 'Rowing Machine',
    primaryMuscleGroup: MuscleGroup.LAT,
    secondaryMuscleGroup: MuscleGroup.BICEPS,
    type: MovementType.CARDIO,
    referenceReps: '500 m',
  },
  {
    id: 'wb',
    name: 'Wall Ball',
    shortName: 'WB',
    difficulty: MovementDifficulty.MEDIUM,
    equipment: 'Medicine Ball',
    primaryMuscleGroup: MuscleGroup.QUADRICEPS,
    secondaryMuscleGroup: MuscleGroup.SHOULDERS,
    type: MovementType.GYMNASTICS,
    referenceReps: '20',
    referenceWeight: '9/6 kg',
  },
  {
    id: 'du',
    name: 'Double Under',
    shortName: 'DU',
    difficulty: MovementDifficulty.HARD,
    equipment: 'Jump Rope',
    primaryMuscleGroup: MuscleGroup.CALVES,
    secondaryMuscleGroup: MuscleGroup.SHOULDERS,
    type: MovementType.CARDIO,
    referenceReps: '100',
  },
  {
    id: 'psq',
    name: 'Pistol Squat',
    shortName: 'PSQ',
    difficulty: MovementDifficulty.HARD,
    equipment: 'None',
    primaryMuscleGroup: MuscleGroup.QUADRICEPS,
    secondaryMuscleGroup: MuscleGroup.GLUTES,
    type: MovementType.GYMNASTICS,
    referenceReps: '10',
  },
  {
    id: 'thr',
    name: 'Thruster',
    shortName: 'THR',
    difficulty: MovementDifficulty.EASY,
    equipment: 'Barbell',
    primaryMuscleGroup: MuscleGroup.QUADRICEPS,
    secondaryMuscleGroup: MuscleGroup.SHOULDERS,
    type: MovementType.WEIGHTLIFTING,
    referenceWeight: '50/35 kg',
    referenceReps: '10',
  },
  {
    id: 'ohs',
    name: 'Overhead Squat',
    shortName: 'OHS',
    difficulty: MovementDifficulty.MEDIUM,
    equipment: 'Barbell',
    primaryMuscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscleGroup: MuscleGroup.QUADRICEPS,
    type: MovementType.WEIGHTLIFTING,
    referenceWeight: '50/35 kg',
    referenceReps: '10',
  },
  {
    id: 'sp',
    name: 'Sled Push',
    shortName: 'SP',
    difficulty: MovementDifficulty.EASY,
    equipment: 'Sled',
    primaryMuscleGroup: MuscleGroup.GLUTES,
    secondaryMuscleGroup: MuscleGroup.QUADRICEPS,
    type: MovementType.STRONGMAN,
    referenceWeight: '100/70 kg',
    referenceReps: '50 m',
  },
  {
    id: 'ttb',
    name: 'Toes-to-Bar',
    shortName: 'TTB',
    difficulty: MovementDifficulty.MEDIUM,
    equipment: 'Pull-up Bar',
    primaryMuscleGroup: MuscleGroup.ABS,
    secondaryMuscleGroup: MuscleGroup.LAT,
    type: MovementType.GYMNASTICS,
    referenceReps: '20',
  },
  {
    id: 'ghd',
    name: 'GHD Sit-up',
    shortName: 'GHD',
    difficulty: MovementDifficulty.MEDIUM,
    equipment: 'GHD Machine',
    primaryMuscleGroup: MuscleGroup.ABS,
    secondaryMuscleGroup: MuscleGroup.HAMSTRINGS,
    type: MovementType.GYMNASTICS,
    referenceReps: '20',
  },
  {
    id: 'sp',
    name: 'Strict Press',
    shortName: 'SP',
    difficulty: MovementDifficulty.MEDIUM,
    equipment: 'Barbell',
    primaryMuscleGroup: MuscleGroup.SHOULDERS,
    secondaryMuscleGroup: MuscleGroup.TRICEPS,
    type: MovementType.WEIGHTLIFTING,
    referenceWeight: '40/30 kg',
    referenceReps: '10',
  },
];

export const scaleDownOptions: Map<MovementId, MovementId> = new Map([
  ['mu', 'pu'],
  ['hspu', 'push-up'],
]);
